services:
  merch_service:
    image: ghcr.io/dmuka/ozon.merchservice:sha256-4ed186e4bc450d3527076783b7c6d40a93ae7644467c358ff3e8ca29942d18e0.sig
    build:
      context: .
      dockerfile: src/Ozon.MerchService/Dockerfile
    ports:
      - name: http
        target: 8080
        published: 5002
          
      - name: grpc
        target: 8081
        published: 5003
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8081;http://+:8080
    command: "-c log_statement=all"

  merch_db:
    image: postgres:latest
    ports: 
      - 5426:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merch_password
      POSTGRES_DB: merch
    command: "-c log_statement=all"
        