services:
  merch_db:
    image: postgres:latest
    ports:
      - 5426:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merch_password
      POSTGRES_DB: merch
    command: "-c log_statement=all"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - merch_db:/var/lib/postgresql/data    
    networks:
      - ozon-network
    
  merch_service:
    image: ozon-merch-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:8080
      - 5003:8081
    environment:
      DBConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5426;Database=merch;Username=postgres;Password=merch_password"
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8081;http://+:8080    
    networks:
      - ozon-network
    depends_on:
      merch_db:
        condition: service_healthy
    entrypoint: ["./wait-for-it.sh", "merch_db:5426", "--", "/bin/bash", "entrypoint.sh"]

  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - ozon-network

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ozon-network     

networks:
  ozon-network:
    driver: bridge

volumes:
  merch_db:
    driver: local