services:
  merch_service:
    image: ghcr.io/dmuka/ozon.merchservice:latest
    build:
      context: .
      dockerfile: src/Ozon.MerchService/Dockerfile
    ports:
      - name: http
        target: 5002
        published: 80
          
      - name: https
        target: 5003
        published: 443
    command: "-c log_statement=all"

  merch_db:
    image: postgres:latest
    ports: 
      - 5426:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merch_password
      POSTGRES_DB: merch
    command: "-c log_statement=all"
        