services:
  merch_service:
    image: ghcr.io/dmuka/ozon.merchservice:sha256-8e301ad7afccea25a1073dbcd048a87a4b5a0edf9b261a020508e2c4c8ae5d75.sig
    build:
      context: .
      dockerfile: src/Ozon.MerchService/Dockerfile
    ports:
      - name: http
        target: 5002
        published: 5002
          
      - name: grpc
        target: 5003
        published: 5003
    command: "-c log_statement=all"

  merch_db:
    image: postgres:latest
    ports: 
      - 5426:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merch_password
      POSTGRES_DB: merch
    command: "-c log_statement=all"
        