services:
  merch_db:
    image: postgres:latest
    ports:
      - 5426:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merch_password
      POSTGRES_DB: merch
    command: "-c log_statement=all"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  merch_service:
    image: ozon-merch-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:8080
      - 5003:8081
    environment:
      DBConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5426;Database=merch;Username=postgres;Password=merch_password"
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8081;http://+:8080
    depends_on:
      merch_db:
        condition: service_healthy
    entrypoint: ["./wait-for-it.sh", "merch_db:5426", "--", "/bin/bash", "entrypoint.sh"]        